import { Router } from 'express';
import { authenticate } from '../middleware/auth.middleware.js';
import { authRouter } from './auth.routes.js';
import { departmentRouter } from './department.routes.js';
import { categoryRouter } from './category.routes.js';
import { employeeRouter } from './employee.routes.js';
import { assetRouter } from './asset.routes.js';
import { allocationRouter } from './allocation.routes.js';
import { bookingRouter } from './booking.routes.js';
import { maintenanceRouter } from './maintenance.routes.js';
import { auditRouter } from './audit.routes.js';
import { notificationRouter } from './notification.routes.js';
import { policyRouter } from './policy.routes.js';
import { reportRouter } from './report.routes.js';

export const router = Router();
router.get('/health', (req, res) => res.json({ status: 'ok' }));
router.use('/auth', authRouter);
router.use('/departments', authenticate, departmentRouter);
router.use('/categories', authenticate, categoryRouter);
router.use('/employees', authenticate, employeeRouter);
router.use('/assets', authenticate, assetRouter);
router.use('/allocations', authenticate, allocationRouter);
router.use('/bookings', authenticate, bookingRouter);
router.use('/maintenance', authenticate, maintenanceRouter);
router.use('/audits', authenticate, auditRouter);
router.use('/notifications', authenticate, notificationRouter);
router.use('/policies', authenticate, policyRouter);
router.use('/reports', authenticate, reportRouter);
