import { Router } from 'express';
import { authenticate } from '../middleware/auth.middleware.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { authRouter } from './auth.routes.js';
import { departmentRouter } from './department.routes.js';
import { categoryRouter } from './category.routes.js';
import { employeeRouter } from './employee.routes.js';
import { assetRouter } from './asset.routes.js';
import { allocationRouter } from './allocation.routes.js';
import { bookingRouter } from './booking.routes.js';
import { maintenanceRouter } from './maintenance.routes.js';
import { auditRouter } from './audit.routes.js';
import { notificationRouter } from './notification.routes.js';
import { policyRouter } from './policy.routes.js';
import { reportRouter } from './report.routes.js';

export const router = Router();
router.get('/health', (req, res) => res.json({ status: 'ok' }));
router.use('/auth', authRouter);
router.use('/departments', asyncHandler(authenticate), departmentRouter);
router.use('/categories', asyncHandler(authenticate), categoryRouter);
router.use('/employees', asyncHandler(authenticate), employeeRouter);
router.use('/assets', asyncHandler(authenticate), assetRouter);
router.use('/allocations', asyncHandler(authenticate), allocationRouter);
router.use('/bookings', asyncHandler(authenticate), bookingRouter);
router.use('/maintenance', asyncHandler(authenticate), maintenanceRouter);
router.use('/audits', asyncHandler(authenticate), auditRouter);
router.use('/notifications', asyncHandler(authenticate), notificationRouter);
router.use('/policies', asyncHandler(authenticate), policyRouter);
router.use('/reports', asyncHandler(authenticate), reportRouter);
